// Arvore de pastas/arquivos do projeto, usada pelo artigo "Estrutura de
// pastas e arquivos" em docs.html (bloco tipo "arvore"). Curada a mao a
// partir da estrutura real do repo - se arquivos forem adicionados/removidos,
// atualize aqui tambem (mesma ressalva de qualquer pagina de documentacao:
// pode ficar desatualizada, confira o repo se tiver duvida).
window.ARVORE_PROJETO = {
  nome: "entrevista",
  tipo: "pasta",
  filhos: [
    { nome: "README.md", tipo: "arquivo", caminho: "README.md",
      descricao: "Como rodar o projeto e as decisões de engenharia tomadas (e por quê) - o entregável principal do desafio." },
    { nome: "CLAUDE.md", tipo: "arquivo", caminho: "CLAUDE.md",
      descricao: "Notas de continuidade do projeto para sessões de IA (Claude Code) futuras - contexto, estado atual, o que falta." },
    { nome: "CHALLENGE.md", tipo: "arquivo", caminho: "CHALLENGE.md",
      descricao: "Enunciado original do desafio técnico (Namastex), copiado sem alterações - referência." },
    { nome: "docker-compose.yml", tipo: "arquivo", caminho: "docker-compose.yml",
      descricao: "Orquestra os 4 serviços (web-ui, agent-service, quote-api, mongo), portas, variáveis de ambiente e volumes persistentes." },
    { nome: ".env.example", tipo: "arquivo", caminho: ".env.example",
      descricao: "Template das variáveis de ambiente (chave da Anthropic, credenciais do Mongo etc.) - copiar para .env e preencher." },
    { nome: ".gitignore", tipo: "arquivo", caminho: ".gitignore",
      descricao: "Exclui .env, __pycache__, logs gerados em runtime etc. do controle de versão." },

    { nome: "agent-service", tipo: "pasta", filhos: [
      { nome: "Dockerfile", tipo: "arquivo", caminho: "agent-service/Dockerfile",
        descricao: "Imagem Python 3.12 do agent-service - instala dependências e roda o Uvicorn." },
      { nome: "pyproject.toml", tipo: "arquivo", caminho: "agent-service/pyproject.toml",
        descricao: "Dependências Python do agent-service (fastapi, anthropic, pymongo, cryptography etc.)." },
      { nome: "app", tipo: "pasta", filhos: [
        { nome: "__init__.py", tipo: "arquivo", caminho: "agent-service/app/__init__.py",
          descricao: "Marca app/ como pacote Python - vazio." },
        { nome: "main.py", tipo: "arquivo", caminho: "agent-service/app/main.py",
          descricao: "Rotas da API FastAPI: conversas, autenticação, config, relatórios, base de conhecimento." },
        { nome: "orchestrator.py", tipo: "arquivo", caminho: "agent-service/app/orchestrator.py",
          descricao: "O coração do agente: máquina de estados, critério de handoff, retry de cotação - toda decisão de negócio mora aqui, nunca no LLM." },
        { nome: "models.py", tipo: "arquivo", caminho: "agent-service/app/models.py",
          descricao: "Dataclasses (Conversation, Message, QuoteAttempt), o enum Status e REQUIRED_SLOTS." },
        { nome: "llm.py", tipo: "arquivo", caminho: "agent-service/app/llm.py",
          descricao: "Cliente da API do Claude: extração estruturada (tool use forçado) e geração de texto livre." },
        { nome: "quote_client.py", tipo: "arquivo", caminho: "agent-service/app/quote_client.py",
          descricao: "Chama o quote-service; distingue sucesso / recusa de negócio / payload inválido / erro de infra (só este último tem retry com backoff)." },
        { nome: "store.py", tipo: "arquivo", caminho: "agent-service/app/store.py",
          descricao: "Conversas em memória (reinicia com o container) + log de eventos append-only em logs/events.jsonl." },
        { nome: "mongo_client.py", tipo: "arquivo", caminho: "agent-service/app/mongo_client.py",
          descricao: "Persistência cifrada (Fernet/AES) de cada evento no MongoDB - mesmo um admin do banco não lê o conteúdo." },
        { nome: "knowledge_base.py", tipo: "arquivo", caminho: "agent-service/app/knowledge_base.py",
          descricao: "Base de conhecimento por casamento de palavras-chave + fila de aprovação (resolução humana entra pendente até um admin aprovar)." },
        { nome: "auth.py", tipo: "arquivo", caminho: "agent-service/app/auth.py",
          descricao: "Usuários do painel interno: cadastro (só admin), senha com hash salgado (PBKDF2), sessão em memória por token." },
        { nome: "config.py", tipo: "arquivo", caminho: "agent-service/app/config.py",
          descricao: "Configuração de negócio editável em runtime pelo Admin (modo de handoff, modelo do Claude, chaves de API) - persistida em JSON." },
        { nome: "relatorios.py", tipo: "arquivo", caminho: "agent-service/app/relatorios.py",
          descricao: "Agregação dos relatórios: filtros por período/nota/atendente, rankings e a série temporal do gráfico." },
      ]},
      { nome: "data", tipo: "pasta", filhos: [
        { nome: "knowledge_base.json", tipo: "arquivo", caminho: "agent-service/data/knowledge_base.json",
          descricao: "Arquivo onde a base de conhecimento é persistida (semente vazia versionada; usuarios.json e runtime_config.json nascem aqui em runtime, não versionados)." },
      ]},
    ]},

    { nome: "quote-service", tipo: "pasta", filhos: [
      { nome: "Dockerfile", tipo: "arquivo", caminho: "quote-service/Dockerfile",
        descricao: "Imagem do serviço de cotação - insumo do desafio." },
      { nome: "pyproject.toml", tipo: "arquivo", caminho: "quote-service/pyproject.toml",
        descricao: "Dependências Python do quote-service." },
      { nome: "uv.lock", tipo: "arquivo", caminho: "quote-service/uv.lock",
        descricao: "Lockfile do uv com as versões exatas resolvidas das dependências." },
      { nome: "app", tipo: "pasta", filhos: [
        { nome: "__init__.py", tipo: "arquivo", caminho: "quote-service/app/__init__.py",
          descricao: "Marca app/ como pacote Python - vazio." },
        { nome: "main.py", tipo: "arquivo", caminho: "quote-service/app/main.py",
          descricao: "Rotas GET /health, GET /planos e POST /quote - simula instabilidade de propósito (QUOTE_FAILURE_RATE/QUOTE_SLOW_RATE)." },
        { nome: "quote_logic.py", tipo: "arquivo", caminho: "quote-service/app/quote_logic.py",
          descricao: "Regras de precificação e de recusa de subscrição (idade/ano do veículo fora da faixa etc.)." },
      ]},
      { nome: "data", tipo: "pasta", filhos: [
        { nome: "plans.json", tipo: "arquivo", caminho: "quote-service/data/plans.json",
          descricao: "Catálogo dos planos (Essencial/Completo/Premium) e suas regras de cotação." },
      ]},
    ]},

    { nome: "web-ui", tipo: "pasta", filhos: [
      { nome: "Dockerfile", tipo: "arquivo", caminho: "web-ui/Dockerfile",
        descricao: "Imagem nginx:alpine que serve os arquivos estáticos do site." },
      { nome: ".dockerignore", tipo: "arquivo", caminho: "web-ui/.dockerignore",
        descricao: "Evita copiar o próprio Dockerfile/nginx.conf para dentro da pasta servida como conteúdo estático." },
      { nome: "nginx.conf", tipo: "arquivo", caminho: "web-ui/nginx.conf",
        descricao: "Desativa cache agressivo de HTML/JS/CSS no navegador, pra nunca ficar vendo versão antiga depois de um deploy." },

      { nome: "index.html", tipo: "arquivo", caminho: "web-ui/index.html",
        descricao: "Landing page pública da AutoSeguro - inclui o markup do widget de chat embutido." },
      { nome: "landing.css", tipo: "arquivo", caminho: "web-ui/landing.css",
        descricao: "Estilo da landing page: hero, planos, seção de vantagens, FAQ, rodapé." },
      { nome: "landing.js", tipo: "arquivo", caminho: "web-ui/landing.js",
        descricao: "Interação da landing page - os botões de cada plano abrem o widget já com uma mensagem pronta." },
      { nome: "widget.css", tipo: "arquivo", caminho: "web-ui/widget.css",
        descricao: "Estilo do chat embutido: bolha flutuante do WhatsApp, painel do chat, gate de reCAPTCHA." },
      { nome: "widget.js", tipo: "arquivo", caminho: "web-ui/widget.js",
        descricao: "Lógica do chat embutido: enviar mensagem, mostrar handoff, badge de não lidas, gate \"não sou um robô\"." },

      { nome: "login.html", tipo: "arquivo", caminho: "web-ui/login.html",
        descricao: "Tela de login do painel interno (atendente/admin)." },
      { nome: "login.css", tipo: "arquivo", caminho: "web-ui/login.css",
        descricao: "Estilo compartilhado do cartão de login (reaproveitado em Usuários e Meus dados também)." },
      { nome: "login.js", tipo: "arquivo", caminho: "web-ui/login.js",
        descricao: "Envia usuário/senha pro backend e guarda a sessão retornada." },

      { nome: "atendente.html", tipo: "arquivo", caminho: "web-ui/atendente.html",
        descricao: "Painel principal do atendente: lista de conversas, detalhe da conversa, base de conhecimento, o menu sanfona." },
      { nome: "atendente.css", tipo: "arquivo", caminho: "web-ui/atendente.css",
        descricao: "Estilo do painel do atendente (lista de conversas, bolhas de mensagem, painéis laterais)." },
      { nome: "atendente.js", tipo: "arquivo", caminho: "web-ui/atendente.js",
        descricao: "Lógica do painel do atendente: polling de conversas, enviar mensagem, finalizar atendimento, aprovar base de conhecimento." },

      { nome: "admin.html", tipo: "arquivo", caminho: "web-ui/admin.html",
        descricao: "Painel de configurações do sistema (Admin)." },
      { nome: "admin.css", tipo: "arquivo", caminho: "web-ui/admin.css",
        descricao: "Estilo dos cartões de configuração e das opções em formato de rádio (modo de handoff etc.)." },
      { nome: "admin.js", tipo: "arquivo", caminho: "web-ui/admin.js",
        descricao: "Lê/salva a configuração: modo de handoff, modelo do Claude, número do WhatsApp, chaves de API, reCAPTCHA." },

      { nome: "usuarios.html", tipo: "arquivo", caminho: "web-ui/usuarios.html",
        descricao: "Menu interno (só admin): formulário de novo usuário + lista dos cadastrados." },
      { nome: "usuarios.css", tipo: "arquivo", caminho: "web-ui/usuarios.css",
        descricao: "Estilo do formulário de cadastro e da lista de usuários (badges de perfil)." },
      { nome: "usuarios.js", tipo: "arquivo", caminho: "web-ui/usuarios.js",
        descricao: "Cria usuários novos (nome, login, senha, perfil, foto) e carrega a lista de cadastrados." },

      { nome: "relatorios.html", tipo: "arquivo", caminho: "web-ui/relatorios.html",
        descricao: "Página de relatórios: filtros, resumo, gráfico e rankings." },
      { nome: "relatorios.css", tipo: "arquivo", caminho: "web-ui/relatorios.css",
        descricao: "Estilo dos filtros, cartões de resumo e linhas de ranking." },
      { nome: "relatorios.js", tipo: "arquivo", caminho: "web-ui/relatorios.js",
        descricao: "Busca o resumo filtrado da API e desenha o gráfico de atendimentos por dia em SVG puro." },

      { nome: "docs.html", tipo: "arquivo", caminho: "web-ui/docs.html",
        descricao: "Este próprio site de documentação interna - layout de 3 colunas (árvore, artigo, índice)." },
      { nome: "docs.css", tipo: "arquivo", caminho: "web-ui/docs.css",
        descricao: "Estilo do site de documentação: árvore lateral, breadcrumb, callouts, blocos de código, índice com scroll-spy." },
      { nome: "docs.js", tipo: "arquivo", caminho: "web-ui/docs.js",
        descricao: "Renderiza os artigos a partir de docs-content.js/docs-arvore.js, controla navegação por hash e o scroll-spy." },
      { nome: "docs-content.js", tipo: "arquivo", caminho: "web-ui/docs-content.js",
        descricao: "Conteúdo dos artigos de documentação (categorias > artigos > blocos de parágrafo/título/lista/código/árvore)." },
      { nome: "docs-arvore.js", tipo: "arquivo", caminho: "web-ui/docs-arvore.js",
        descricao: "Este arquivo - a árvore de pastas/arquivos do projeto usada no artigo \"Estrutura de pastas e arquivos\"." },

      { nome: "meus-dados.html", tipo: "arquivo", caminho: "web-ui/meus-dados.html",
        descricao: "Página onde qualquer usuário logado troca a própria foto de perfil." },
      { nome: "meus-dados.css", tipo: "arquivo", caminho: "web-ui/meus-dados.css",
        descricao: "Estilo da pré-visualização da foto e dos botões de salvar/remover." },
      { nome: "meus-dados.js", tipo: "arquivo", caminho: "web-ui/meus-dados.js",
        descricao: "Lê a foto escolhida, salva/remove via API e atualiza a sessão e a bolinha da topbar na hora." },

      { nome: "styles.css", tipo: "arquivo", caminho: "web-ui/styles.css",
        descricao: "Tokens de design (cores, espaçamento, tipografia) e componentes compartilhados por todas as páginas: topbar, botões, avatar, menu sanfona." },
      { nome: "config.js", tipo: "arquivo", caminho: "web-ui/config.js",
        descricao: "Define a URL base da API do agent-service que o front-end usa (configurável em Admin, guardada no navegador)." },
      { nome: "auth.js", tipo: "arquivo", caminho: "web-ui/auth.js",
        descricao: "Sessão do painel interno: getSessao/exigirLogin/logoutStaff e o botão de mostrar/ocultar senha - compartilhado por todas as páginas internas." },
      { nome: "avatar.js", tipo: "arquivo", caminho: "web-ui/avatar.js",
        descricao: "Desenha o círculo de avatar (foto ou img/userdefault.jpg), lê fotos escolhidas como data URI, e a bolinha clicável da topbar." },
      { nome: "menu.js", tipo: "arquivo", caminho: "web-ui/menu.js",
        descricao: "Abre/fecha o menu sanfona (hamburguer) da topbar e o botão Sair - genérico, compartilhado por todas as páginas internas." },
      { nome: "tab-badge.js", tipo: "arquivo", caminho: "web-ui/tab-badge.js",
        descricao: "Favicon dinâmico com contador de não lidas e o sininho de notificação sintetizado (Web Audio)." },
      { nome: "speech.js", tipo: "arquivo", caminho: "web-ui/speech.js",
        descricao: "Integração do botão de microfone com a Web Speech API (fala vira texto)." },

      { nome: "img", tipo: "pasta", filhos: [
        { nome: "userdefault.jpg", tipo: "arquivo", caminho: "web-ui/img/userdefault.jpg",
          descricao: "Cópia redimensionada (256x256) do avatar padrão - a que o site realmente serve." },
      ]},
    ]},

    { nome: "dataset", tipo: "pasta", filhos: [
      { nome: "DICIONARIO.md", tipo: "arquivo", caminho: "dataset/DICIONARIO.md",
        descricao: "Esquema/dicionário de dados do dataset de conversas sintéticas - insumo do desafio." },
      { nome: "conversations.parquet", tipo: "arquivo", caminho: "dataset/conversations.parquet",
        descricao: "~2500 conversas sintéticas lead↔vendedor - insumo do desafio, não usado diretamente pelo agente em runtime." },
      { nome: "sample.jsonl", tipo: "arquivo", caminho: "dataset/sample.jsonl",
        descricao: "Amostra do dataset em JSONL, mais fácil de espiar sem abrir o parquet." },
    ]},

    { nome: "docs", tipo: "pasta", filhos: [
      { nome: "fluxograma-agente.drawio", tipo: "arquivo", caminho: "docs/fluxograma-agente.drawio",
        descricao: "Fluxograma completo do agente (abrir em draw.io): NLU, gate de handoff, retry de cotação, loop de aprendizado da base de conhecimento." },
    ]},

    { nome: "scripts", tipo: "pasta", filhos: [
      { nome: "generate_dataset.py", tipo: "arquivo", caminho: "scripts/generate_dataset.py",
        descricao: "Script que gera o dataset sintético de conversas - insumo do desafio." },
    ]},

    { nome: "img", tipo: "pasta", filhos: [
      { nome: "userdefault.jpg", tipo: "arquivo", caminho: "img/userdefault.jpg",
        descricao: "Imagem original (fonte, alta resolução) do avatar padrão - a cópia redimensionada que o site realmente serve fica em web-ui/img/." },
    ]},
  ],
};
